import os

TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")
DB_PATH = os.getenv("DB_PATH", "finance_bot.db")

(
    WAITING_CATEGORY_NAME,
    WAITING_ACCOUNT_NAME,
    WAITING_ACCOUNT_BALANCE,
    WAITING_STATS_CUSTOM_DATE,
    WAITING_TRANSACTION_AMOUNT,
    WAITING_TRANSACTION_DATE_CUSTOM,
    WAITING_TRANSFER_AMOUNT,
    WAITING_TRANSFER_DATE_CUSTOM,
    WAITING_DELETE_TRANSACTION,
    WAITING_DELETE_TRANSFER,
) = range(10)
